title: Open Source Dev.
author: Nirmal Kumar Joshi
email: nirmalkjoshi99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey readers, I Nirmal Kumar Joshi welcome you to the blog page on open source.

# social links
twitter_username: @NirmalJoshi99
github_username:  NirmalKumarJoshi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
